#!/usr/bin/env bash
set -euo pipefail

# ci-build.sh [Debug|Release]
BUILD_TYPE="${1:-Debug}"
CPPSTD="23"

echo "[ci-build] Build type: ${BUILD_TYPE}"

# Conan profile + install for the requested build type
conan --version || true
conan profile detect --force || conan profile detect || true
conan install . -s build_type="${BUILD_TYPE}" -s compiler.cppstd="${CPPSTD}" --build=missing

# Use CMakePresets generated by Conan
PRESET="conan-$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')"

echo "[ci-build] Configure with preset: ${PRESET}"
cmake --preset "${PRESET}"

echo "[ci-build] Build with preset: ${PRESET}"
cmake --build --preset "${PRESET}" -j

# Run tests from the expected build folder per cmake_layout
BUILD_DIR="build/${BUILD_TYPE}"

echo "[ci-build] Run tests in: ${BUILD_DIR}"
ctest --test-dir "${BUILD_DIR}" --output-on-failure
