name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Test inside Dev Container (${{ matrix.build_type }})
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/ci/devcontainer.json
          runCmd: |
            bash scripts/build.sh "${{ matrix.build_type }}"

      - name: Upload coverage (Debug only)
        if: matrix.build_type == 'Debug'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build/Debug/coverage
          if-no-files-found: warn
