name: Coverage

on:
  # Run on PRs to main or manually; avoid duplicate runs on branch pushes
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Coverage inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.ci.json
          runCmd: |
            chmod +x scripts/ci-coverage.sh || true
            scripts/ci-coverage.sh

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: build/Coverage/coverage
